### ISSUE TITLE
LinkedIn and GitHub link values are hardcoded always rendered as [mikhail-liamets]

### ISSUE THREAD

**Issue by crosskayla** [caffeinatedgaze/bare-bone-cv#1]
# Issue
PDFs always generate with "mikhail-liamets" as the LinkedIn link text and "caffeintazedgaze" as the GitHub link text.

<img width="144" alt="image" src="https://github.com/caffeinatedgaze/bare-bones-cv/assets/35676639/544a359a-f630-4fda-999d-3725ba8a7aff">

# Details
The sources of this issue are the hardcoded values in `/main.typ`:
```
LinkedIn: #link(configuration.contacts.linkedin)[mikhail-liamets] \
GitHub: #link(configuration.contacts.github)[caffeintazedgaze] \
```

# Potential fixes

- Could pass the linkedin & github values as a dict `(url: "https://.com", displayText: "myusername")` and then use `configuration.contacts.github.displayText instead of the hardcoded value
- Could do some fancy url splicing :) 

I am happy to open a PR if you'd like contributors. 

_Note: thanks very much for the template. I've really enjoyed using it._

**Comment by caffeinatedgaze** [comment]
Thank you for opening this issue. Contributions are of course welcome! The template is very raw indeed
